<?php
/**
 * Created by PhpStorm.
 * User: megatron
 * Date: 2017/9/20
 * Time: 下午2:06
 */
include_once "tools.php";

class MyMaxHeap extends SplMaxHeap{
    public function compare($value1, $value2)
    {
        parent::compare($value1, $value2); // TODO: Change the autogenerated stub
    }
}

$heap = new MyMaxHeap();

$heap->insert('a');
$heap->insert('b');
$heap->insert('c');

pp($heap);